easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Person
        - App\Entity\Role
#        - App\Entity\Category
#        - App\Entity\User
    formats:
        date:     'Y-m-d'
        time:     'H:i'
        datetime: 'Y-m-d H:i:s'