lexik_jwt_authentication:
    private_key_path: '%kernel.root_dir%/../%env(resolve:JWT_PRIVATE_KEY_PATH)%'
    public_key_path:  '%kernel.root_dir%/../%env(resolve:JWT_PUBLIC_KEY_PATH)%'
    pass_phrase:      '%env(resolve:JWT_PASSPHRASE)%'
    token_ttl:        '%env(resolve:JWT_TOKEN_TTL)%'