security:
    role_hierarchy:
        ROLE_READER: ROLE_USER
        ROLE_ADMIN: ROLE_READER
    encoders:
#        Silpion\VacationBundle\Entity\User:
#            algorithm:  sha512
        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: ryanpass
                        roles: 'ROLE_USER'
                    admin:
                        password: kitten
                        roles: 'ROLE_ADMIN'
    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api/*
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - App\Security\Guard\JWTTokenAuthenticator
        admin:
            pattern: ^/admin
            anonymous: true

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/*,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin,       roles: ROLE_ADMIN }
